### Cvičení s knihovnami Pandas a Numpy

# Úvod
Tento notebook obsahuje sérii cvičení zaměřených na knihovny `numpy` a `pandas`. Cvičení začínají základními operacemi a postupně přecházejí k pokročilejším tématům.

## Požadavky
Před začátkem cvičení si nainstalujte potřebné knihovny, pokud je ještě nemáte.

## Dataset ke stažení
[DataSet](https://www.kaggle.com/datasets/samithsachidanandan/1000-most-subscribed-youtube-channels-in-germany)

In [1]:
!pip install numpy pandas

## 1. Základní operace s numpy

### 1.1 Vytvoření pole a základní operace
Numpy umožňuje vytvářet efektivní numerická pole a provádět s nimi operace.


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)  # (5,)
print(arr.dtype)  # int64
print(arr.sum())  # 15
print(arr.mean())  # 3.0

(5,)
int64
15
3.0


#### Cvičení:
Vytvořte numpy pole `arr` obsahující čísla od 1 do 10. Poté proveďte následující operace:
- Vypište tvar a datový typ pole
- Sečtěte všechny prvky v poli
- Vypočítejte průměr prvků
- Najděte maximální a minimální hodnotu


In [3]:
# TODO: Vytvořte numpy pole a proveďte operace
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr.shape)
print(arr.dtype)
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

(10,)
int64
55
5.5
10
1


In [4]:
matrix = np.random.randint(1, 100, (3,3))
print(matrix)
print(matrix.sum())
print(matrix.max(axis=1))  # Max hodnoty pro každý řádek
print(matrix.T)  # Transponovaná matice

[[69 23 13]
 [ 6 47 28]
 [86 46 71]]
389
[69 47 86]
[[69  6 86]
 [23 47 46]
 [13 28 71]]



### 1.2 Operace s maticemi
Numpy umožňuje pracovat s vícerozměrnými maticemi.

#### Příklad:
```python
matrix = np.random.randint(1, 100, (3,3))
print(matrix)
print(matrix.sum())
print(matrix.max(axis=1))  # Max hodnoty pro každý řádek
print(matrix.T)  # Transponovaná matice
```


#### Cvičení:
Vytvořte 3x3 matici s náhodnými celými čísly od 1 do 100 a proveďte následující operace:
- Vypište celou matici
- Vypište součet všech prvků
- Najděte největší prvek v každém řádku
- Změnte hodnoty, které jsou vyšší než 50 na 0 a vypište matici



In [12]:
# TODO: Vytvořte a analyzujte matici
matrix = np.random.randint(1, 100, (3,3))
print(matrix)
print(matrix.sum())
print(matrix.max(axis=1))
print("\n")
print(np.where(matrix > 50, 0, matrix))


[[83 76 60]
 [27 87 71]
 [74 80 94]]
652
[83 87 94]


[[ 0  0  0]
 [27  0  0]
 [ 0  0  0]]


## 2. Základy pandas

### 2.1 Vytvoření DataFrame
Pandas umožňuje vytvářet tabulková data pomocí `DataFrame`.

#### Příklad:
```python
import pandas as pd
data = {'Jméno': ['Adam', 'Eva', 'Karel', 'Jana'], 'Věk': [25, 30, 22, 28], 'Město': ['Praha', 'Brno', 'Ostrava', 'Plzeň']}
df = pd.DataFrame(data)
print(df)
```


#### Cvičení:
Vytvořte `DataFrame` obsahující následující údaje:


| Jméno  | Třída | Ročník     |
|--------|----|-----------|
| Adam   | IT1 | 1     |
| Eva    | IT2 | 2      |
| Karel  | ES3 | 3   |
| Jana   | EP4 | 4     |







In [13]:
# TODO: Vytvořte DataFrame
import pandas as pd
data = {'Jméno': ['Adam', 'Eva', 'Karel', 'Jana'], 'Třída': ['IT1', 'IT2', 'ES3', 'EP4'], 'Ročník': [1, 2, 3, 4]}
df = pd.DataFrame(data)
print(df)

   Jméno Třída  Ročník
0   Adam   IT1       1
1    Eva   IT2       2
2  Karel   ES3       3
3   Jana   EP4       4


### 2.2 Práce s DataFrame

#### Příklad:
```python
print(df['Věk'].mean())  # Průměrný věk
df['Zaměstnání'] = ['Programátor', 'Učitel', 'Student', 'Doktor']
print(df[df['Věk'] > 25])  # Filtrování
```


#### Cvičení:
Na předchozím `DataFrame` proveďte následující operace:
- Získejte průměrný věk
- Přidejte nový sloupec `Zaměstnání` s hodnotami `Programátor, Učitel, Student, Doktor`
- Vyfiltrujte osoby starší než 25 let



In [ ]:
# TODO: Proveďte operace s DataFrame


#### Cvičení:
Vytvořte tento dataFrame:


| Jméno  | Věk |
|--------|----|
| Adam   | 18 |
| Eva    | 13 |
| Karel  | 80 |
| Jana   | 60 |




a udělejte na něm následující operace:
- Získejte počty unikátních zaměstnání
- Přidejte nový sloupec `Zaměstnání` s hodnotami `Programátor, Učitel, Student, Doktor`
- Přidejte nový řádek/ záznam
- Vyfiltrujte osoby starší než 25 let nebo jsou doktory
- vypište první řádek
- mezi každým úkolem bude řádek z -

In [16]:
import pandas as pd
data = {'Jméno': ['Adam', 'Eva', 'Karel', 'Jana'], 'Věk': [18, 13, 80, 60]}
df = pd.DataFrame(data)
print(df)
print()
print(df['Věk'].mean())
df['Zaměstnání'] = ['Programátor', 'Učitel', 'Student', 'Doktor']
print(df[df['Věk'] > 25])
print()
print(df['Zaměstnání'].nunique())
df.loc[len(df)] = ['Karel', 22, 'Student']
print(df)
print()
print(df[(df['Věk'] > 25) | (df['Zaměstnání'] == 'Doktor')])
print()
print(df.head(1))


   Jméno  Věk
0   Adam   18
1    Eva   13
2  Karel   80
3   Jana   60

42.75
   Jméno  Věk Zaměstnání
2  Karel   80    Student
3   Jana   60     Doktor

4
   Jméno  Věk   Zaměstnání
0   Adam   18  Programátor
1    Eva   13       Učitel
2  Karel   80      Student
3   Jana   60       Doktor
4  Karel   22      Student

   Jméno  Věk Zaměstnání
2  Karel   80    Student
3   Jana   60     Doktor

  Jméno  Věk   Zaměstnání
0  Adam   18  Programátor


## 3. Pokročilejší operace

### 3.1 Načítání dat ze souboru

#### Příklad:
```python
df = pd.read_csv('data.csv')
print(df.head())
```





#### Cvičení:
Načtěte tento soubor do `DataFrame` a vypište první tři řádky: Viz příloha případně si vytvořte soubor a napište do něj toto:



`Jméno,Věk,Město,Zaměstnání`

`Adam,25,Praha,Programátor`

`Eva,30,Brno,Učitel`

`Karel,22,Ostrava,Student`

`Jana,28,Plzeň,Doktor`

`Karel,22,Brno,Učitel`



In [18]:
# TODO: Načtěte CSV soubor
df = pd.read_csv('data.csv')
print(df.head(3))


   Jméno  Věk    Město   Zaměstnání
0   Adam   25    Praha  Programátor
1    Eva   30     Brno       Učitel
2  Karel   22  Ostrava      Student



### 3.2 Agregace dat

#### Cvičení:
Z daného `DataFrame` proveďte následující operace:
- Spočítejte počet unikátních měst
- Skupinová analýza podle města – spočítejte průměrný věk v každém městě


In [19]:
# TODO: Proveďte agregace
print(df['Město'].nunique())
print(df.groupby('Město')['Věk'].mean())


4
Město
Brno       30.0
Ostrava    22.0
Plzeň      28.0
Praha      25.0
Name: Věk, dtype: float64


## **Samostatná úloha: Analýza YouTube kanálů v Německu**

### **1. Načtení a prozkoumání datasetu**
- Načtěte dataset do `pandas.DataFrame`
- Zobrazte prvních 5 řádků datasetu
- Vypište základní informace o datech

```python
# TODO: Načtěte dataset a prozkoumejte ho
```

### **2. Čištění a příprava dat**
- Zkontrolujte dataset na chybějící hodnoty
- Převádějte hodnoty ve sloupcích na správné datové typy

```python
# TODO: Vyčistěte data
```

### **3. Analýza a vizualizace dat**
- Kolik je v datasetu unikátních kategorií YouTube kanálů?
- Které 3 kategorie mají nejvíce kanálů?
- Jaký je průměrný počet odběratelů na kanál?
- Najděte 10 největších YouTube kanálů v Německu

```python
# TODO: Proveďte analýzu a vizualizace
```

### **4. Pokročilá analýza**
- Vypočítejte medián a rozptyl počtu odběratelů
- Které město má nejvíce populárních YouTube kanálů?
- Porovnejte průměrný počet odběratelů mezi různými kategoriemi

```python
# TODO: Proveďte pokročilou analýzu
```

### **5. Extra úkol – vytvoření nového sloupce**
- Přidejte nový sloupec `Popularity Score`
- Seřaďte dataset podle tohoto skóre a vypište top 10 kanálů

```python
# TODO: Vytvořte nový sloupec a analyzujte ho
```